In [2]:
# file handling
# read
# update
print("hello")

hello


In [19]:
from google.colab import drive
# drive.mount('/content/drive')

# read data
data = open("/content/drive/MyDrive/file1.csv","r")
data.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [39]:
# write and read
data2 = open("/content/drive/MyDrive/hello.txt","w")
data2.write("we are indians also aryains ")

data2 = open("/content/drive/MyDrive/hello.txt","r")
data2.read()

'we are indians also aryains '

In [44]:
# read and append
data2 = open("/content/drive/MyDrive/hello.txt","r")
data2.read()

data2 = open("/content/drive/MyDrive/hello.txt","a")
data2.write(" we are grrasian \n")

data2 = open("/content/drive/MyDrive/hello.txt","r")
data2.read()

# csv

'we are indians also aryains  we are grrasian \n we are grrasian \n we are grrasian \n we are grrasian \n'

In [45]:
# direct access without drive
data = open("hello.txt","r")
data.read()

'hello file handling\n'

In [47]:
# direct access csv file
data1 = open("file1.csv","r")
data1.read()

# write and append

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [55]:
# numpy
# !pip install numpy
import numpy as np
# 1d
l = [10,20,30,40]
l*2

# power of numpy
arr = np.array(l)
arr*2

array([20, 40, 60, 80])

In [64]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr[0])
print(arr[-1])

[1 2 3 4]
1
4


In [68]:
import numpy as np
# check type
l = [10,20,30,40]
print(l)
print(type(l))

arr = np.array(l)
print(arr)
print(type(arr))

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [72]:
# change value
import numpy as np
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)
# numpy
arr = np.array(l)
arr[0] = 200
arr[-1] = 250
print(arr)

[100, 20, 30, 150]
[200  20  30 250]


In [76]:
# value add = 2
import numpy as np
l = [10,20,30,40]
# print(l+2) # add not acceptable with list

arr = np.array(l)
print(arr+2)

[12 22 32 42]


In [86]:
# arange in numpy
import numpy as np
arr = np.arange(5) # start,stop,jump
print(arr)

arr = np.arange(1,7,2)
print(arr)

[0 1 2 3 4]
[1 3 5]


In [84]:
for i in range(1,5):
  print(i)

1
2
3
4


In [91]:
# simple 2d example
import numpy as np
print("list start")
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0][1]) # -> 2
print("numpy start")
# numpy 2d
arr = np.array(l)
print(arr)
print(arr[0][0])

list start
[[1, 2, 3], [4, 5, 6]]
2
numpy start
[[1 2 3]
 [4 5 6]]
1
